using System.Net;

namespace GarminAchievements;

/// <summary>Bits every public page shares: how to reach the operator and the footer with the legal links.
/// SUPPORT_EMAIL (env; PRIVACY_CONTACT is the older name) is the contact; without it, the GitHub issues page.</summary>
public static class Site
{
    public static string? ContactFromEnvironment() =>
        Environment.GetEnvironmentVariable("SUPPORT_EMAIL") is { Length: > 0 } email
            ? email
            : Environment.GetEnvironmentVariable("PRIVACY_CONTACT");

    public static string ContactHtml(string? contact)
    {
        if (string.IsNullOrWhiteSpace(contact))
            return "<a href=\"https://github.com/yohananha/WatchCrawler/issues\">github.com/yohananha/WatchCrawler/issues</a>";
        var safe = WebUtility.HtmlEncode(contact.Trim());
        return contact.Contains('@') ? $"<a href=\"mailto:{safe}\">{safe}</a>" : safe;
    }

    public static string Footer(string? contact) => $"""
        <footer class="site">
          <nav><a href="/">WatchCrawler</a> · <a href="/terms">Terms</a> · <a href="/refunds">Refunds</a> · <a href="/privacy">Privacy</a> · <a href="/unlock">Unlock</a></nav>
          <p>Contact: {ContactHtml(contact)}</p>
          <p>Payments are processed by Lemon Squeezy, our merchant of record.</p>
        </footer>
        """;

    /// <summary>The look of the text pages (privacy, terms, refunds).</summary>
    public const string TextStyle = """
          :root { color-scheme: light dark; }
          body { font-family: system-ui, sans-serif; max-width: 680px; margin: 32px auto; padding: 0 16px; line-height: 1.55; }
          h1 { font-size: 1.6rem; margin-bottom: 2px; }
          h2 { font-size: 1.15rem; margin-top: 28px; }
          .muted { opacity: .7; }
          a { color: #6a5cff; }
          footer.site { margin-top: 40px; padding-top: 14px; border-top: 1px solid #8884; font-size: .9rem; opacity: .8; }
          footer.site p { margin: 4px 0; }
        """;
}

/// <summary>GET /terms and GET /refunds. Keep them in step with what the server does (Hosted.cs, Licensing)
/// and with the numbers in HostedSettings.</summary>
public static class LegalPages
{
    public const string Updated = "2026-10-07";
    public const int RefundDays = 14;

    public static string Terms(HostedSettings s, string? contact) => Fill(TermsTemplate, s, contact);
    public static string Refunds(HostedSettings s, string? contact) => Fill(RefundsTemplate, s, contact);

    private static string Fill(string template, HostedSettings s, string? contact) => template
        .Replace("{{STYLE}}", Site.TextStyle)
        .Replace("{{FOOTER}}", Site.Footer(contact))
        .Replace("{{CONTACT}}", Site.ContactHtml(contact))
        .Replace("{{UPDATED}}", Updated)
        .Replace("{{REFUND_DAYS}}", RefundDays.ToString())
        .Replace("{{PRICE}}", s.PriceUsd.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture))
        .Replace("{{TRIAL_DAYS}}", s.TrialDays.ToString())
        .Replace("{{YEARS}}", s.LicenseYears.ToString())
        .Replace("{{PER_DAY}}", s.AiPerDay.ToString());

    private const string TermsTemplate = """
        <!doctype html>
        <html lang="en">
        <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>WatchCrawler terms of service</title>
        <link rel="icon" href="/img/cover-500.png">
        <style>{{STYLE}}</style>
        </head>
        <body>
        <h1>WatchCrawler terms of service</h1>
        <p class="muted">Last updated {{UPDATED}}</p>

        <p>WatchCrawler is a Garmin Connect IQ watch app, made and run by Yohanan Haik ("we"). It turns your activity
        into short, sarcastic RPG-style achievements. By installing the app or buying an unlock you agree to these terms.</p>

        <h2>The free app and the trial</h2>
        <p>The app is free to install from the Garmin Connect IQ Store. Each watch gets a free {{TRIAL_DAYS}}-day trial of
        AI-written achievements, starting the first time it reaches our server. After the trial the app keeps working
        with its built-in lines.</p>

        <h2>What the unlock gives you</h2>
        <ul>
          <li>A one-time payment of ${{PRICE}} (plus any sales tax or VAT shown at checkout). No subscription, no renewal.</li>
          <li>{{YEARS}} years of AI-written achievements for <b>one watch</b>, the one whose 6-character code you entered
          at checkout, starting on the day of purchase.</li>
          <li>Up to {{PER_DAY}} AI-written achievements a day; beyond that, and after the {{YEARS}} years, the app uses its
          built-in lines.</li>
        </ul>
        <p>The texts are generated by an AI model. They are meant as jokes, are not medical, fitness or training advice,
        and may occasionally be odd or wrong.</p>

        <h2>Payment</h2>
        <p>Purchases are sold and processed by Lemon Squeezy, our merchant of record, which also handles taxes, receipts
        and refunds. Their terms apply to the checkout itself.</p>

        <h2>Refunds</h2>
        <p>Refunds are available within {{REFUND_DAYS}} days of purchase, no questions asked. See the
        <a href="/refunds">refund policy</a>.</p>

        <h2>Fair use</h2>
        <p>Don't try to get around the trial, the daily limit or the licence (for example by faking device ids), or
        to overload, probe or misuse the server. We may block watches that do.</p>

        <h2>Changes to the service</h2>
        <p>We may improve or change the app and the server. If we ever shut down the AI narration before your
        {{YEARS}} years are up, you will get a pro-rata refund for the remaining time on request.</p>

        <h2>No warranty, limited liability</h2>
        <p>The app and service are provided "as is". The AI narration depends on the internet, your phone's connection to
        the watch, and third-party services, so it may sometimes be unavailable. To the extent the law allows, our total
        liability is limited to the amount you paid for the unlock. Nothing here limits rights you have as a consumer
        under the law of your country.</p>

        <h2>Privacy</h2>
        <p>See the <a href="/privacy">privacy policy</a> for what data is used and why.</p>

        <h2>Contact</h2>
        <p>{{CONTACT}}</p>

        {{FOOTER}}
        </body>
        </html>
        """;

    private const string RefundsTemplate = """
        <!doctype html>
        <html lang="en">
        <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>WatchCrawler refund policy</title>
        <link rel="icon" href="/img/cover-500.png">
        <style>{{STYLE}}</style>
        </head>
        <body>
        <h1>WatchCrawler refund policy</h1>
        <p class="muted">Last updated {{UPDATED}}</p>

        <h2>{{REFUND_DAYS}} days, no questions asked</h2>
        <p>If you're not happy with your unlock for any reason, you can get a full refund within {{REFUND_DAYS}} days of
        purchase.</p>

        <h2>How to ask</h2>
        <ul>
          <li>Reply to your Lemon Squeezy receipt email, or</li>
          <li>write to {{CONTACT}} with your order number or the 6-character code shown on your watch.</li>
        </ul>
        <p>The refund goes back to your original payment method through Lemon Squeezy, usually within 5-10 business
        days depending on your bank. When the refund goes through, that watch's unlock ends and the app goes back to its
        built-in lines.</p>

        <h2>After {{REFUND_DAYS}} days</h2>
        <p>If the app stops working on your watch because of a problem on our side, write to us and we'll fix it or refund
        you. If we ever shut down the AI narration before your {{YEARS}} years are up, you'll get a pro-rata refund for
        the remaining time on request.</p>

        {{FOOTER}}
        </body>
        </html>
        """;
}
